-- Seed questions for NakedTruth
insert into public.questions (tier, kind, prompt)
values
  ('tier_1', 'frequency_1_5', 'Jak moc tě štvou moji rodiče nebo rodina? (1 = vůbec, miluju je, 5 = nemůžu je vystát)'),
  ('tier_1', 'yes_no', 'Máš pocit, že ve vztahu momentálně táhneš víc finančních nákladů než já?'),
  ('tier_1', 'short_answer', 'Který můj každodenní zvyk tě neskutečně vytáčí, ale zatím jsi to držel/a v sobě?'),
  ('tier_1', 'yes_no', 'Dokázal/a bys mi odpustit jednorázovou fyzickou nevěru na firemním večírku, kdybych se hned přiznal/a?'),
  ('tier_1', 'frequency_1_5', 'Jak moc je pro tebe důležité trávit víkendy občas odděleně se svými přáteli? (1 = chci být pořád spolu, 5 = potřebuju svůj vlastní víkend hodně často)'),
  ('tier_1', 'yes_no', 'Zatajil/a jsi mi někdy nějaký větší dluh nebo finanční průšvih?'),
  ('tier_1', 'short_answer', 'Co si myslíš, že je aktuálně nejslabší místo našeho vztahu?'),
  ('tier_1', 'frequency_1_5', 'Jak moc ti vadí, když piju alkohol nebo si dám trávu? (1 = vůbec, 5 = vadí mi to hodně)'),
  ('tier_1', 'yes_no', 'Díváš se občas do mého telefonu nebo na zprávy, když se nedívám?'),
  ('tier_1', 'yes_no', 'Měl/a jsi někdy během našeho vztahu moment, kdy sis vážně říkal/a, že se rozejdeme?'),
  ('tier_1', 'frequency_1_5', 'Jak moc tě uspokojuje to, jak si dělíme domácí práce? (1 = všechno dělám já, 5 = je to naprosto fér)'),
  ('tier_1', 'short_answer', 'Kdyby sis mohl/a na mě změnit jednu jedinou povahovou vlastnost, co by to bylo?'),
  ('tier_1', 'yes_no', 'Udržuješ tajně kontakt s někým, do koho jsi byl/a v minulosti zamilovaný/á?'),
  ('tier_1', 'frequency_1_5', 'Jak moc jsi žárlivý/á, když se bavím s někým atraktivním opačného/stejného pohlaví? (1 = vůbec to neřeším, 5 = vaří se ve mně krev)'),
  ('tier_1', 'yes_no', 'Chceš mít v budoucnu (další) děti? Pokud už je máme, platí to pro další potomky.'),
  ('tier_1', 'short_answer', 'Jaká je největší lež, kterou jsi mi kdy řekl/a?'),
  ('tier_1', 'frequency_1_5', 'Jak moc ti záleží na tom, jak vypadám a jak se oblékám na veřejnosti? (1 = je mi to jedno, 5 = chci, abys mě reprezentoval/a)'),
  ('tier_1', 'yes_no', 'Máš pocit, že mě musíš občas ''vychovávat'' jako dítě?'),
  ('tier_1', 'yes_no', 'Lákalo by tě zkusit žít na pár let v zahraničí?'),
  ('tier_1', 'short_answer', 'Co tě na mně na začátku vztahu nejvíc přitahovalo a dělá to pořád?'),
  ('tier_1', 'frequency_1_5', 'Jak moc ambiciózní podle tebe jsem? (1 = gaučový povaleč, 5 = workoholik, co jde přes mrtvoly)'),
  ('tier_1', 'yes_no', 'Vadí ti moje stravovací návyky nebo to, jak se starám o své tělo?'),
  ('tier_1', 'short_answer', 'Co je tvůj největší nesplněný životní sen, o kterém si myslíš, že ho kvůli mně nezrealizuješ?'),
  ('tier_1', 'yes_no', 'Cítíš se být ve vztahu s mými přáteli komfortně? (Tedy s mojí partou)'),
  ('tier_1', 'frequency_1_5', 'Jak moc jsi spokojený/á s tím, jak trávíme společné večery doma? (1 = nuda k uzoufání, 5 = absolutní spokojenost)'),
  ('tier_1', 'yes_no', 'Flirtuješ občas s kolegy nebo cizími lidmi, jen aby sis zvedl/a sebevědomí?'),
  ('tier_1', 'short_answer', 'Kdybys mohl/a zítra opustit svou práci a peníze by nebyly problém, co bys dělal/a?'),
  ('tier_1', 'yes_no', 'Máš pocit, že jsem tě někdy citově vydíral/a?'),
  ('tier_1', 'frequency_1_5', 'Do jaké míry věříš, že spolu zůstaneme až do konce života? (1 = spíš ne, 5 = jsem si tím naprosto jistý/á)'),
  ('tier_1', 'short_answer', 'Za co ze své minulosti se nejvíc stydíš?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi aktuálně spokojený/á s frekvencí našeho sexu? (1 = je ho hrozně málo, 5 = je to naprosto ideální)'),
  ('tier_2', 'yes_no', 'Sleduješ pravidelně porno?'),
  ('tier_2', 'short_answer', 'Jaký typ porna tě vzrušuje nejvíc a nikdy jsi mi to neřekl/a?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká vyzkoušet anální sex? (1 = ani náhodou, 5 = chci to hned/chci to častěji)'),
  ('tier_2', 'yes_no', 'Předstíral/a jsi se mnou někdy orgasmus?'),
  ('tier_2', 'short_answer', 'Kde na veřejnosti by sis nejvíc přál/a mít sex?'),
  ('tier_2', 'frequency_1_5', 'Jak moc otevřený/á jsi polyamory nebo otevřenému vztahu? (1 = nikdy, zabilo by mě to, 5 = dává mi to smysl)'),
  ('tier_2', 'yes_no', 'Líbí se ti, když tě při sexu tahám za vlasy nebo ti dám lehký pohlavek/výprask?'),
  ('tier_2', 'yes_no', 'Měl/a jsi někdy sexuální sny o někom z našich společných přátel?'),
  ('tier_2', 'frequency_1_5', 'Jak moc ráda bys zkusil/a lehký choking (škrcení) při sexu? (1 = ne, bojím se toho, 5 = vzrušuje mě to maximálně)'),
  ('tier_2', 'short_answer', 'Co bychom měli přidat do naší předehry, aby to pro tebe bylo lepší?'),
  ('tier_2', 'yes_no', 'Láká tě používání análních kolíků nebo jiných hraček do zadku (ať už na mně, nebo na tobě)?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi dominantní/submisivní? (1 = chci naprosto ovládat, 5 = chci se nechat plně ovládat)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě představa, že by nás někdo při sexu tajně sledoval (voyeurismus)?'),
  ('tier_2', 'short_answer', 'Která sexuální poloha tě se mnou vlastně vůbec nebaví, ale děláme ji?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys, abych polykal/a (při orálním sexu)?'),
  ('tier_2', 'frequency_1_5', 'Jak moc by sis chtěl/a vyzkoušet svazování (bondage)? (1 = vůbec, 5 = chci být přivázán/a k posteli na fest)'),
  ('tier_2', 'yes_no', 'Lákalo tě někdy vyzkoušet si sex se stejným pohlavím (nebo do toho jít znovu, pokud už to znáš)?'),
  ('tier_2', 'short_answer', 'Co je tvoje ''guilty pleasure'' při masturbaci?'),
  ('tier_2', 'frequency_1_5', 'Jak moc ti vyhovuje dirty talk (sprosté mluvení) při sexu? (1 = chci ticho/romantiku, 5 = chci slyšet ty nejsprostší věci)'),
  ('tier_2', 'yes_no', 'Poslal/a bys mi rád/a svoje nahé fotky, nebo chceš, abych je posílal/a já tobě?'),
  ('tier_2', 'yes_no', 'Zkusil/a bys rád/a sex v přírodě nebo v lese, kde je riziko, že nás někdo uvidí?'),
  ('tier_2', 'frequency_1_5', 'Nakolik iniciuješ sex ty v porovnání se mnou? (1 = čekám na tebe, 5 = jsem to většinou já, kdo začíná)'),
  ('tier_2', 'short_answer', 'Jakou sexuální hračku (vibrátor, pouta, dildo, atd.) bychom si měli co nejdříve pořídit?'),
  ('tier_2', 'yes_no', 'Představoval/a sis mě někdy při sexu s někým jiným?'),
  ('tier_2', 'yes_no', 'Vadí ti chutnat moje tělní tekutiny?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká ranní sex rovnou po probuzení? (1 = potřebuju si vyčistit zuby a dát kafe, 5 = hned na mě skoč)'),
  ('tier_2', 'yes_no', 'Máš rád/a, když tě při sexu natáčím nebo fotím?'),
  ('tier_2', 'short_answer', 'Kdy přesně jsi se mnou zažil/a absolutně nejlepší sex?'),
  ('tier_2', 'yes_no', 'Láká tě hrát si s teplotou (led na tělo, horký vosk)?'),
  ('tier_1', 'frequency_1_5', 'Jak často mě v duchu srovnáváš se svými bývalými partnery? (1 = vůbec nikdy, 5 = dělám to docela často)'),
  ('tier_1', 'yes_no', 'Máš nějaký tajný finanční účet, rezervu nebo úspory, o kterých nevím?'),
  ('tier_1', 'short_answer', 'Který můj názor na výchovu dětí nebo chod rodiny ti přijde úplně mimo?'),
  ('tier_1', 'frequency_1_5', 'Jak moc toxické ti připadají naše hádky? (1 = hádáme se konstruktivně, 5 = lítají talíře a padají krutá slova)'),
  ('tier_1', 'yes_no', 'Existuje v tvé rodině nějaké dědičné onemocnění nebo psychický problém, o kterém ses mi zatím bál/a říct?'),
  ('tier_1', 'short_answer', 'Jaký můj zlozvyk v koupelně nebo ohledně osobní hygieny tě fakt štve?'),
  ('tier_1', 'frequency_1_5', 'Jak moc velký problém by pro tebe byl, kdybych přibral/a 15 kilo a nechtěl/a to řešit? (1 = miloval bych tě stejně, 5 = přestal bys mě fyzicky přitahovat)'),
  ('tier_1', 'yes_no', 'Předstíráš občas, že mě posloucháš, když ti něco vyprávím, ale ve skutečnosti myslíš na něco jiného?'),
  ('tier_1', 'yes_no', 'Cítil/a ses někdy v našem vztahu tak osaměle, že jsi hledal/a emocionální oporu u někoho jiného?'),
  ('tier_1', 'short_answer', 'Který z mých kamarádů nebo kamarádek ti je vyloženě nesympatický a proč?'),
  ('tier_1', 'frequency_1_5', 'Jak moc ti vadí, když trávím čas na mobilu, když jsme spolu? (1 = je mi to fuk, 5 = připadám si ignorovaný/á)'),
  ('tier_1', 'yes_no', 'Smazal/a jsi někdy konverzaci s někým na chatu dřív, než bych ji mohl/a vidět?'),
  ('tier_1', 'yes_no', 'Myslíš si, že bychom měli jít do párové terapie, i když zrovna neřešíme obrovskou krizi?'),
  ('tier_1', 'short_answer', 'Kdybys mi mohl/a zakázat jednu věc, kterou dělám ve volném čase, co by to bylo?'),
  ('tier_1', 'frequency_1_5', 'Jak moc věříš tomu, že umím hospodařit s penězi? (1 = věřím ti na 100 %, 5 = jsi chodící katastrofa)'),
  ('tier_1', 'yes_no', 'Měl/a jsi někdy pocit, že jsem tě ztrapnil/a před tvými přáteli nebo rodinou?'),
  ('tier_1', 'short_answer', 'Co nejtěžšího jsi musel/a v životě překonat a měl/a jsi pocit, že jsem tě v tom dostatečně nepodpořil/a?'),
  ('tier_1', 'frequency_1_5', 'Jak moc důležitá je pro tebe svatba a papír na náš vztah? (1 = nepotřebuju to, 5 = je to pro mě zásadní cíl)'),
  ('tier_1', 'yes_no', 'Kdybych onemocněl/a a zůstal/a na vozíku, zvládl/a bys se o mě starat a zůstat se mnou?'),
  ('tier_1', 'yes_no', 'Existuje téma, o kterém se se mnou bojíš mluvit, protože víš, že hned vyletím?'),
  ('tier_1', 'frequency_1_5', 'Do jaké míry cítíš, že měníš svou osobnost jen proto, aby ses mi zavděčil/a? (1 = jsem to 100% já, 5 = dost se přetvařuju)'),
  ('tier_1', 'short_answer', 'Jak bys popsal/a náš vztah jedním, naprosto upřímným (i nehezkým) slovem?'),
  ('tier_1', 'yes_no', 'Máš pocit, že po mně musíš doma uklízet věci víc, než je zdrávo?'),
  ('tier_1', 'yes_no', 'Bál/a ses někdy mé reakce natolik, že jsi mi radši zalhal/a?'),
  ('tier_1', 'frequency_1_5', 'Jak hodnotíš mou inteligenci a všeobecný přehled oproti svému? (1 = jsi chytřejší, 5 = připadám si vedle tebe jako génius)'),
  ('tier_1', 'short_answer', 'Kdybychom se zítra rozešli, co by ti na mně chybělo ze všeho nejmíň?'),
  ('tier_1', 'yes_no', 'Změnily se tvoje politické nebo náboženské názory během našeho vztahu tak, že by to mohl být problém?'),
  ('tier_1', 'frequency_1_5', 'Jak moc ti vadí moje sociální bublina (koho sleduju na sítích, co čtu)? (1 = sdílíme to, 5 = přijde mi to hrozné)'),
  ('tier_1', 'yes_no', 'Máš pocit, že mě moje práce ničí, a já to nevidím?'),
  ('tier_1', 'short_answer', 'Jaký společný zážitek byl pro tebe naprostým utrpením, ačkoliv já si myslel/a, že se skvěle bavíme?'),
  ('tier_2', 'frequency_1_5', 'Při sexu ve třech: preferoval/a bys kombinaci MFF (dvě ženy, muž) nebo MMF (dva muži, žena)? (1 = jenom dvě ženy a já, 5 = jenom dva muži a já)'),
  ('tier_2', 'yes_no', 'Byl by pro tebe problém mít sex, když máš zrovna menstruaci (nebo ji mám já)?'),
  ('tier_2', 'short_answer', 'Kde přesně na svém těle bys chtěl/a, abych při orgasmu skončil/a (např. do obličeje, dovnitř, na prsa)?'),
  ('tier_2', 'frequency_1_5', 'Láká tě představa peggingu (kdy žena análně proniká do muže pomocí strap-onu)? (1 = absolutní odpor, 5 = velmi mě to vzrušuje)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě představa ''cuckoldingu'', tedy že bys mě sledoval/a při sexu s někým jiným?'),
  ('tier_2', 'short_answer', 'Kdy jsi naposledy masturboval/a a na co (nebo na koho) jsi při tom myslel/a?'),
  ('tier_2', 'frequency_1_5', 'Jak otevřený/á jsi hrátkám s močí (golden shower)? (1 = hnusí se mi to, 5 = láká mě to zkusit)'),
  ('tier_2', 'yes_no', 'Měl/a jsi někdy v minulosti sex za peníze (nebo jsi za něj platil/a) a zatajil/a jsi mi to?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys, abychom zkusili zavedení pravidla, že masturbace je povolena jen s mým souhlasem (chastity/orgasm denial)?'),
  ('tier_2', 'short_answer', 'Které sprosté slovo tě v posteli nejvíc nakopne, když ti ho zašeptám (nebo zařvu) do ucha?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká použití roubíku (gag) nebo zavázání očí (blindfold) při sexu? (1 = děsí mě to, 5 = to musíme mít)'),
  ('tier_2', 'yes_no', 'Vadí ti moje ochlupení, nebo bys naopak chtěl/a, abych se holil/a na určitých místech jinak?'),
  ('tier_2', 'yes_no', 'Líbí se ti, když tě při sexu natvrdo ponižuji (degradation) nebo ti říkám jmény jako ''děvko'' apod.?'),
  ('tier_2', 'short_answer', 'Jaká je tvoje nejméně oblíbená věc na orálním sexu, který ti dělám?'),
  ('tier_2', 'frequency_1_5', 'Jak moc preferuješ ''quickies'' (rychlovky) oproti dlouhému milování? (1 = miluju jen dlouhé maratony, 5 = klidně 3 minuty v kuchyni a stačí)'),
  ('tier_2', 'yes_no', 'Máš pocit, že jsem v posteli občas až moc sobecký/á a myslím hlavně na svůj orgasmus?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys někdy zkusit sex pod vlivem nějaké lehčí drogy (MDMA, extáze, tráva) pro zintenzivnění prožitku?'),
  ('tier_2', 'short_answer', 'Jaký kousek oblečení nebo spodního prádla na mně tě okamžitě dostane do varu?'),
  ('tier_2', 'frequency_1_5', 'Jak moc by s ti líbilo, kdybych tě někdy ve spánku vzbudil/a tím, že ti už rovnou dělám orál nebo do tebe vniknu (somnophilia)? (1 = v žádném případě, 5 = to je obrovská fantazie)'),
  ('tier_2', 'yes_no', 'Máš nějaké trauma z minulosti spojené se sexem, o kterém bych měl/a vědět, ale bojíš se mi to říct?'),
  ('tier_2', 'frequency_1_5', 'Chtěl/a bys, abychom zkusili swingers párty, kde se nebudeme míchat s ostatními, ale budeme mít sex vedle jiného páru v jedné místnosti? (1 = ne, 5 = absolutně ano)'),
  ('tier_2', 'short_answer', 'Kdybys mohl/a z našich intimních chvilek vymazat jednu trapnou nebo nepříjemnou situaci, co by to bylo?'),
  ('tier_2', 'yes_no', 'Používal/a jsi někdy během našeho vztahu nějakou online seznamku jen ze zvědavosti nebo kvůli ''egu''?'),
  ('tier_2', 'yes_no', 'Vzrušuje tě představa zkoušení různých teplot při sexu (např. kapaní horkého vosku na kůži)?'),
  ('tier_2', 'frequency_1_5', 'Jak moc je pro tebe vizuální stimulace důležitá (světlo, zrcadla kolem postele)? (1 = radši úplnou tmu, 5 = chci nás u toho celou dobu vidět)'),
  ('tier_2', 'short_answer', 'Je nějaká část mého těla, o které víš, že z ní mám mindrák, ale tobě přijde neuvěřitelně sexy?'),
  ('tier_2', 'yes_no', 'Zkusil/a bys rád/a sex na místech, kde je to vyloženě zakázané nebo riskantní (zkušební kabinka, letadlo, výtah)?'),
  ('tier_2', 'yes_no', 'Je pro tebe důležité po sexu ležet a mazlit se (aftercare), nebo si radši jdeš dát hned sprchu a spát?'),
  ('tier_2', 'frequency_1_5', 'Jak moc by sis přál/a, kdybych během sexu občas převzal/a absolutní kontrolu a nedal/a ti na výběr, co se bude dít? (1 = nemám rád/a ztrátu kontroly, 5 = přesně tohle potřebuju)'),
  ('tier_2', 'short_answer', 'Kdybychom měli mít sex naposledy v životě a mohl/a by sis vybrat naprosto cokoliv, jak by ten večer vypadal?'),
  ('tier_1', 'frequency_1_5', 'Jak těžké je pro tebe mluvit se mnou o tom, co přesně v sexu chceš? (1 = vůbec, nemám problém, 5 = je to pro mě obrovský blok)'),
  ('tier_1', 'yes_no', 'Bál/a ses někdy navrhnout novou sexuální praktiku, protože by sis myslel/a, že mě to znechutí nebo to odsoudím?'),
  ('tier_1', 'short_answer', 'Která tvoje fyzická nejistota nebo mindrák z vlastního těla tě v posteli nejvíc brzdí?'),
  ('tier_1', 'yes_no', 'Měl/a jsi někdy pocit, že se mnou spíš z povinnosti nebo abych měl/a klid, než z reálné chuti?'),
  ('tier_1', 'frequency_1_5', 'Jak moc tě vzrušuje představa, že bych tě jen tiše sledoval/a, jak masturbuješ? (1 = vůbec, stydím se, 5 = hrozně moc)'),
  ('tier_1', 'yes_no', 'Vadí ti, když po tobě chci sex v momentech, kdy víš, že jsem předtím pil/a alkohol?'),
  ('tier_1', 'short_answer', 'Jaké gesto, slovo nebo dotek mimo ložnici (přes den) tě zaručeně naladí na večerní sex?'),
  ('tier_1', 'frequency_1_5', 'Jak moc je pro tebe důležitá absolutní čistota (sprcha, zuby) těsně před tím, než se začneme milovat? (1 = neřeším to, přirozenost je sexy, 5 = bez sprchy na mě nesahej)'),
  ('tier_1', 'yes_no', 'Skrýval/a jsi přede mnou někdy nákup nebo vlastnictví sexuální hračky?'),
  ('tier_1', 'yes_no', 'Máš někdy pocit, že naše intimita zevšedněla a stala se z ní předvídatelná rutina?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká vyzkoušet si sex na veřejném místě, kde je reálné riziko přistižení? (1 = ani náhodou, 5 = vyhledávám to)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě představa, že bys měl/a zavázané oči a nevěděl/a, co přesně a čím ti budu dělat?'),
  ('tier_2', 'short_answer', 'Jakou roli by sis chtěl/a zahrát v rámci roleplay (např. šéf/podřízená, doktor/pacientka, cizinci v baru)?'),
  ('tier_2', 'yes_no', 'Lákalo by tě zkusit si během sexu natáčet jen hlasové nahrávky (audio vzdychání a sprostého mluvení) místo videa?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi otevřený/á používání jídla nebo nápojů (šlehačka, čokoláda, led, víno) při předehře? (1 = patlá se to a lepí, ne, 5 = chci to ze mě slízat)'),
  ('tier_2', 'yes_no', 'Zkusil/a bys rád/a sex v zaparkovaném autě v noci, i kdyby to mělo být stísněné a nepohodlné?'),
  ('tier_2', 'short_answer', 'Která sexuální praktika z porna ti přijde fyzicky náročná nebo nereálná, ale tajně bys ji chtěl/a zažít?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě vzrušuje představa, že bych si přivedl/a dalšího partnera jen proto, abys nás mohl/a z rohu místnosti sledovat? (1 = vůbec, 5 = splněný sen)'),
  ('tier_2', 'yes_no', 'Líbí se ti, když na tobě záměrně zanechám viditelné stopy po sexu (cucfleky, škrábance, otisky rukou)?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys někdy zkusit tantrický sex, tedy dlouhé hodiny pomalého milování a doteků s cílem oddálit orgasmus co nejdéle?'),
  ('tier_2', 'short_answer', 'Jaký nejkurióznější předmět v domácnosti jsi ve svém životě použil/a k masturbaci, když jsi neměl/a hračky?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi pro to, abychom do ložnice nainstalovali zrcadla, abychom se při sexu viděli z více úhlů? (1 = nesnáším se sledovat, 5 = to musíme mít)'),
  ('tier_2', 'yes_no', 'Vzrušovalo by tě, kdybych ti nečekaně během dne poslal/a do práce hlasovku, kde přesně sprostě popisuju, co s tebou večer provedu?'),
  ('tier_2', 'yes_no', 'Dosáhl/a jsi někdy (nebo chtěl/a bys) orgasmu jen díky stimulaci bradavek nebo jiných zón mimo samotné genitálie?'),
  ('tier_2', 'short_answer', 'Co je pro tebe absolutní ''turn-off'' (okamžitý zabiják vzrušení) přímo v průběhu sexu?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká zkusit anální stimulaci (prsty, menší hračky) v rámci předehry, i kdyby to nevedlo přímo k análnímu styku? (1 = na to mi nesahej, 5 = dělej to co nejčastěji)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě, když tě při sexu oslovuji vulgárními výrazy, které bych normálně nikdy nepoužil/a?'),
  ('tier_2', 'yes_no', 'Lákalo by tě zkusit ''orgasm control'' – tedy nechat mě plně rozhodovat o tom, jestli a kdy vůbec smíš dosáhnout orgasmu?'),
  ('tier_2', 'short_answer', 'Kdybys mohl/a zkusit sex s jakoukoliv žijící celebritou a já bych ti dal/a ''beztrestnou propustku na jednu noc'', kdo by to byl?'),
  ('tier_2', 'frequency_1_5', 'Jak moc by se ti líbilo, kdybychom si občas dali ''sexuální půst'' (např. dva týdny naprosto bez sexu a masturbace), aby to pak bylo výbušnější? (1 = to bych nevydržel/a, 5 = skvělý nápad)'),
  ('tier_2', 'yes_no', 'Používáš rád/a lubrikanty se speciálním efektem (chladivé, hřejivé, vibrační)?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys zkusit sex na místě, kde je hodně hluku nebo lidí, ale my jsme schovaní (např. zamčení na záchodě v přeplněném klubu)?'),
  ('tier_2', 'short_answer', 'Jaká je tvoje vůbec nejerotičtější vzpomínka na nás dva z doby, kdy jsme spolu teprve začínali randit?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi pro používání lehkých BDSM úderových pomůcek, jako jsou kožené plácačky (paddles) nebo malé bičíky? (1 = nechci bolest, 5 = štípej mě pořádně)'),
  ('tier_2', 'yes_no', 'Vyhovuje ti, když tě při sexu nutím nahlas a do detailu popisovat, co přesně fyzicky cítíš, když do tebe vstupuju / se tě dotýkám?'),
  ('tier_2', 'yes_no', 'Preferuješ při sexu zapnutou hudbu v pozadí, nebo máš raději úplné ticho, kde slyšíš jen zvuky našich těl a dechu?'),
  ('tier_2', 'short_answer', 'Kdybychom teď byli v luxusním sexshopu a já ti řekl/a, ať do košíku hodíš jednu věc bez ohledu na cenu, co by to bylo?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká vyzkoušet si edging (záměrné dohánění těsně na okraj orgasmu a následné zastavení stimulace) pro prodloužení konečné rozkoše? (1 = je to frustrující, 5 = miluju to)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě představa, že bys mi plivnul/a do úst (nebo já tobě) během tvrdšího sexu?'),
  ('tier_2', 'yes_no', 'Baví tě dynamický sex, kdy měníme polohy rychle za sebou, nebo se raději ztratíš v jedné poloze na delší dobu?'),
  ('tier_2', 'short_answer', 'Co si myslíš o myšlence, že bychom společně zkusili natočit a prodat nějaký náš anonymní erotický obsah (např. na OnlyFans) čistě pro zábavu a adrenalin?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi otevřený/á tomu, že bychom se nazí natřeli masážním olejem od hlavy až k patě a klouzali po sobě (Nuru masáž)? (1 = hnusí se mi ta mastnota, 5 = chci se klouzat celou noc)'),
  ('tier_2', 'yes_no', 'Líbí se ti, když tě při ranním vstávání začnu dráždit a osahávat ještě dřív, než úplně otevřeš oči a probereš se?'),
  ('tier_2', 'yes_no', 'Měl/a jsi někdy fantazii o tom, že za tebou přijdu nečekaně do práce a máme rychlý sex přímo na tvém pracovním stole?'),
  ('tier_2', 'short_answer', 'Co konkrétně bych měl/a víc dělat svýma rukama během toho, co se milujeme v klasických polohách?'),
  ('tier_2', 'frequency_1_5', 'Jak moc bys ocenil/a, kdybych pro nás nečekaně objednal/a hotelový pokoj v našem městě jen za účelem celonočního sexu? (1 = zbytečné vyhazování peněz, 5 = nejlepší rande vůbec)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě přirozená vůně mého potu těsně po tom, co přijdu z fitka nebo ze sportu, ještě před sprchou?'),
  ('tier_2', 'yes_no', 'Zkusil/a bys rád/a sex ve vodě (ve vaně, v bazénu, v nočním moři), i přes to, že to často drhne a není to moc praktické?'),
  ('tier_2', 'short_answer', 'Kdybys mi měl/a dát upřímnou známku od 1 do 10 za to, jak ti dělám orální sex, jaká by to byla a co udělat, aby to byla čistá 10?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká zkusit ''pet play'' (hraní zvířecích rolí, např. nošení obojku, vodítka) v posteli? (1 = to je na mě už moc divné, 5 = zajímá mě to/vzrušuje)'),
  ('tier_2', 'yes_no', 'Chtěl/a bys, abych tě někdy při sexu přivázal/a tak pevně a důkladně, že se opravdu nebudeš moct vůbec pohnout?'),
  ('tier_2', 'yes_no', 'Je ti příjemné, když se na sebe při vyvrcholení upřeně díváme do očí, nebo máš radši u orgasmu zavřené oči?'),
  ('tier_2', 'short_answer', 'Kdy a kde jsi se mnou zažil/a největší adrenalin spojený s možností, že nás při sexu někdo nachytá?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká vyzkoušet stimulaci prostaty (pokud jsi muž) nebo hlubokou stimulaci G-bodu (pokud jsi žena) pomocí k tomu určené tvarované hračky? (1 = nechci, 5 = nutně to musíme pořídit)'),
  ('tier_2', 'yes_no', 'Chtěl/a bys, abychom zavedli a striktně používali tzv. ''bezpečnostní slovo'' (safeword) pro případ, že začneme experimentovat s bolestí nebo omezováním?'),
  ('tier_2', 'yes_no', 'Vzrušovalo by tě, kdybychom šli do restaurace na večeři a ty bys měl/a pod oblečením vibrátor, který bych já pod stolem ovládal/a přes aplikaci?'),
  ('tier_2', 'short_answer', 'Kterou specifickou (klidně i netradiční) věc na mém těle nejraději líbáš, olizuješ nebo okusuješ?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi otevřený/á používání svorek na bradavky (nipple clamps) pro zvýšení citlivosti a lehkou bolest? (1 = au, ne, 5 = nasadit a tahat)'),
  ('tier_2', 'yes_no', 'Je pro tebe zásadní tzv. ''aftercare'', tedy to, že tě po tvrdším sexu ještě dlouze hladím, masíruji ti záda a ujišťuji tě o citech?'),
  ('tier_2', 'yes_no', 'Máš nějakou skrytou sexuální fantazii spojenou s uniformami (policista, voják, zdravotní sestra, letuška)?'),
  ('tier_1', 'yes_no', 'Zalhal/a jsi mi někdy záměrně o tom, s kým přesně jsi šel/šla ven, abych nezačal/a žárlit?'),
  ('tier_1', 'short_answer', 'Za jakou naprostou zbytečnost podle tebe utrácím nejvíc peněz?'),
  ('tier_1', 'frequency_1_5', 'Jak moc si dokážeš představit, že by s námi někdy v budoucnu pod jednou střechou bydlela moje matka/otec? (1 = ani za nic, 5 = bez problému)'),
  ('tier_1', 'yes_no', 'Děsí tě, jak bude moje tělo vypadat za 10 nebo 20 let?'),
  ('tier_1', 'yes_no', 'Máš pocit, že ti vyčítám, když si chceš udělat čas jen na svoje koníčky a odpočinout si ode mě?'),
  ('tier_1', 'yes_no', 'Když ti napíše tvůj/tvoje ex, řekneš mi to vždycky, nebo už jsi mi zprávu někdy raději zatajil/a?'),
  ('tier_1', 'frequency_1_5', 'Jak moc tě momentálně fyzicky přitahuje někdo konkrétní z tvé práce nebo okolí? (1 = vůbec nikdo, 5 = myslím na něj/ni docela často)'),
  ('tier_1', 'short_answer', 'Jaká je tvoje tajná ''zbraň'', kterou používáš, když víš, že mě chceš v hádce opravdu vytočit nebo zranit?'),
  ('tier_1', 'yes_no', 'Použil/a jsi někdy sex nebo fyzickou blízkost jako odměnu, nebo mi ji odepřel/a jako trest?'),
  ('tier_1', 'frequency_1_5', 'Jak často v těžkých chvílích lituješ, že jsme se vůbec dali dohromady? (1 = nikdy, 5 = při každé větší hádce)'),
  ('tier_1', 'yes_no', 'Dokázal/a bys mi odpustit, kdybych ti ve velmi vyhrocené hádce v afektu vlepil/a facku?'),
  ('tier_1', 'short_answer', 'V jakých situacích ti můj smysl pro humor připadá absolutně nevhodný nebo trapný?'),
  ('tier_1', 'frequency_1_5', 'Jak velký respekt ke mně cítíš, když řešíme vážné životní problémy? (1 = mám tě za dítě, 5 = absolutně tě respektuji)'),
  ('tier_1', 'short_answer', 'Jaký byl pro tebe zatím nejtěžší kompromis, který jsi musel/a kvůli našemu vztahu udělat?'),
  ('tier_1', 'yes_no', 'Přetvařuješ se záměrně před mými rodiči, abys u nich vypadal/a lépe?'),
  ('tier_1', 'frequency_1_5', 'Do jaké míry máš občas pocit, že jsi v našem vztahu ''ten lepší/chytřejší/úspěšnější''? (1 = jsme si rovni, 5 = táhnu to já)'),
  ('tier_1', 'yes_no', 'Změnil/a jsi kvůli mně svůj životní styl tak moc, že to vlastně uvnitř nenávidíš?'),
  ('tier_1', 'yes_no', 'Kdybys měl/a možnost, kontroloval/a bys mi preventivně výpisy z bankovního účtu?'),
  ('tier_1', 'frequency_1_5', 'Když se hádáme, jak moc je pro tebe důležité ''vyhrát'' a mít poslední slovo? (1 = vůbec, chci klid, 5 = musím mít pravdu)'),
  ('tier_1', 'short_answer', 'Jakou jednu konkrétní věc bych měl/a zítra začít dělat, abys cítil/a, že tě stoprocentně miluju a podporuju?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě baví sledovat společně porno a zkoušet napodobit přesně to, co v něm vidíme? (1 = je to trapné, 5 = super vzrušující)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě představa vzájemné masturbace, kdy ležíme vedle sebe, nedotýkáme se a jen se na sebe díváme?'),
  ('tier_2', 'short_answer', 'Jaký konkrétní reálný zvuk (mlaskání, vzdychání, plácání kůže) tě v posteli nejvíc a nejrychleji nadrží?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi otevřený/á lízání konečníku (rimming)? (1 = hnus, ani mě nenapadne, 5 = miluju to dávat/přijímat)'),
  ('tier_2', 'yes_no', 'Vadí ti pomyšlení na to, že bych ti při vyvrcholení nastříkal/a na obličej (cum on face)?'),
  ('tier_2', 'yes_no', 'Lákalo by tě zaplatit si společně profesionálního/profesionální eskort/prostitutku pro sex ve třech (abychom do toho nepletli emoce a kamarády)?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě přitahuje foot fetish (vzrušení z chodidel, masírování, sání prstů na nohou)? (1 = nohy jsou fuj, 5 = to je moje úchylka)'),
  ('tier_2', 'short_answer', 'Kdybys mi měl/a přidělit nějaký vulgární nebo ponižující titul/přezdívku, kterou bych tě musel/a v posteli oslovovat, jaká by to byla?'),
  ('tier_2', 'yes_no', 'Chceš zkusit natočit naše domácí video na mobil s tím, že si ho pošleme do práce v době oběda?'),
  ('tier_2', 'frequency_1_5', 'Láká tě fantazie ''znásilnění'' po vzájemném souhlasu (consensual non-consent / CNC), kdy se bráníš, ale já tě stejně ''donutím''? (1 = z toho mám hrůzu, 5 = obrovská fantazie)'),
  ('tier_2', 'yes_no', 'Když máš chuť na sex, ale bojíš se odmítnutí, potlačíš to v sobě a raději jdeš spát nebo se uspokojíš sám/sama?'),
  ('tier_2', 'short_answer', 'Která část naší obvyklé předehry je pro tebe vlastně už nuda a nejraději bys ji přeskočil/a?'),
  ('tier_2', 'frequency_1_5', 'Pokud bys měl/a zkusit (nebo opakovat) pegging s dildem, jak moc by tě to bavilo? (1 = ani za milion, 5 = chci to hned zkusit)'),
  ('tier_2', 'yes_no', 'Chtěl/a bys, abych tě někdy při sexu dusil/a (choking) tak silně, až budeš lapat po dechu?'),
  ('tier_2', 'yes_no', 'Vzrušuje tě myšlenka ''nuceného polykání'', kdy tě držím za vlasy a nedovolím ti uhnout?'),
  ('tier_2', 'short_answer', 'Máš na těle místo, kam absolutně nesnášíš, když ti sahám, ale nikdy jsi mi to pořádně nevysvětlil/a?'),
  ('tier_2', 'frequency_1_5', 'Jak jsi otevřený/á ''female ejaculation'' (squirtu)? (1 = je mi to nepříjemné/mokré, 5 = chci to dělat/chci tě k tomu přivést)'),
  ('tier_2', 'yes_no', 'Byl by pro tebe sex ve sprše nebo na ručníku plně akceptovatelný i během nejsilnějšího dne tvé/mé menstruace?'),
  ('tier_2', 'frequency_1_5', 'Jak moc se ti líbí představa, že bys na sobě měl/a latexové, kožené nebo vinylové oblečky? (1 = potím se, ne, 5 = přijde mi to neskutečně hot)'),
  ('tier_2', 'yes_no', 'Chtěl/a bys zkusit rande, kdy se setkáme v baru jako naprostí cizinci a ''sbalíme'' se s úplně vymyšlenou identitou?'),
  ('tier_2', 'short_answer', 'Když ležíme v posteli před milováním, co je tvůj největší vnitřní strach (např. že ztratím erekci, že budu smrdět, že nepřijdu)? '),
  ('tier_2', 'frequency_1_5', 'Mile high club: láká tě vyzkoušet si rychlovku na malém záchodě v letadle i přes riziko ostudy? (1 = moc práce a bakterií, 5 = chci to odškrtnout ze seznamu)'),
  ('tier_2', 'yes_no', 'Chtěl/a bys být součástí hromadné orgie/sex párty, kde by nás mohlo ''použít'' více lidí najednou?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká fantazie ''cuckolding'', tedy že bys mě s mým svolením podvedl/a s někým lepším/větším a já tě pak za to musel/a uctívat? (1 = divný bizár, 5 = obrovské vzrušení)'),
  ('tier_2', 'yes_no', 'Líbí se ti představa, že si tě vezmu natvrdo zezadu uprostřed dne, třeba když zrovna vaříš nebo myješ nádobí, bez jakéhokoliv varování?'),
  ('tier_2', 'short_answer', 'Jaký byl tvůj naposledy erotický sen o mně a co přesně se v něm dělo?'),
  ('tier_2', 'frequency_1_5', 'Jak otevřený/á jsi kousání do citlivých partií (krk, stehna, břicho), které zanechá silné stopy? (1 = nechci bolest, 5 = označkuj si mě)'),
  ('tier_2', 'yes_no', 'Láká tě používání elektrostimulace (elektrošoky na bradavky nebo genitálie pro zvýšení bolesti i citlivosti)?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys někdy použít tzv. ''glory hole'', kde nevidíš partnera na druhé straně zdi, ale dochází k uspokojení?'),
  ('tier_2', 'frequency_1_5', 'Jak moc si libuješ v myšlence, že bys mi plně odevzdal/a kontrolu nad svými financemi a osobním životem výměnou za to, že budu tvůj Pán/Paní (Total Power Exchange)? (1 = ani náhodou, chci svobodu, 5 = je to můj ultimátní fetiš)'),
  ('tier_2', 'short_answer', 'Pokud bys mohl/a zkusit sex s mým/tvojí nejlepším kamarádem/kamarádkou bez toho, abych to kdy zjistil/a, udělal/a bys to?'),
  ('tier_2', 'yes_no', 'Baví tě, když během orálního sexu schválně dělám ''deep throat'' tak hluboko, až se mi zvedá žaludek / dávíš mě?'),
  ('tier_2', 'frequency_1_5', 'Láká tě zkoušet hrátky s vycpávkami, kolíky na kalhotkách nebo nosit butt plug celý den v práci? (1 = nepohodlné, 5 = chci být tajně nadržený/á celý den)'),
  ('tier_2', 'yes_no', 'Kdybys věděl/a, že to stoprocentně neudělá zlou krev, chtěl/a bys sdílet mou/svou ex s námi v jedné posteli?'),
  ('tier_2', 'short_answer', 'Jakou konkrétní nadávku bych ti měl/a říct přesně v momentě, kdy do mě poprvé vnikáš / kdy přijímám vniknutí?'),
  ('tier_2', 'frequency_1_5', 'Jak moc se ti líbí představa, že bys hrál/a roli ''služky'' nebo ''sluhy'', který musí splnit jakýkoliv můj rozkaz dříve, než mě může uspokojit? (1 = nechci se ponižovat, 5 = miluju tu dynamiku)'),
  ('tier_2', 'yes_no', 'Stěžoval/a jsi si někdy svým kamarádům na to, jaký jsem (nebo nejsem) v posteli?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys zkusit sex v opuštěné budově, v lese mimo cesty nebo v nějaké zřícenině, kde je reálné riziko zranění a tmy?'),
  ('tier_2', 'short_answer', 'Pokud bys mě musel/a vzrušit pouze slovy během jedné minuty přes telefon, co přesně bys mi řekl/a?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi pro myšlenku otevřít si ''hall pass'' – dovolit si jednou za rok sex s někým jiným bez následků? (1 = absolutní ne, zničilo by nás to, 5 = velmi mě to láká)'),
  ('tier_1', 'yes_no', 'Přál/a sis někdy tajně, abych vydělával/a víc peněz, abys ty nemusel/a tolik pracovat nebo se stresovat?'),
  ('tier_1', 'frequency_1_5', 'Jak moc v duchu soudíš mé přátele nebo lidi, se kterými se stýkám? (1 = vůbec, mám je rád/a, 5 = myslím si, že to jsou idioti)'),
  ('tier_1', 'short_answer', 'Jakou tvoji osobní hranici občas překročím, aniž bych si to vůbec uvědomil/a?'),
  ('tier_1', 'yes_no', 'Prohledával/a jsi mi někdy fyzické věci (šuplíky, skříň, kapsy), když jsem nebyl/a doma?'),
  ('tier_1', 'frequency_1_5', 'Jak upřímně tě zajímají moje koníčky a to, o čem ti nadšeně vyprávím? (1 = vůbec mě to nezajímá, jen přikyvuju, 5 = miluju to poslouchat)'),
  ('tier_1', 'short_answer', 'Kdybychom se zítra v klidu rozešli, jaký by byl ten hlavní, ''oficiální'' důvod, který bys řekl/a rodině?'),
  ('tier_1', 'yes_no', 'Stydíš se za mě občas, když se ve společnosti opiju nebo jsem trochu víc ''naladěný/á''?'),
  ('tier_1', 'yes_no', 'Předstíral/a jsi někdy nemoc nebo únavu jen proto, abys nemusel/a jít na sraz s mojí rodinou nebo mými přáteli?'),
  ('tier_1', 'frequency_1_5', 'Jak moc jistý/á se cítíš ohledně své pozice v mém životě oproti mé kariéře a mým dalším povinnostem? (1 = cítím se na vedlejší koleji, 5 = vím, že jsem absolutní priorita)'),
  ('tier_1', 'short_answer', 'Jaká je ta nejvíc zraňující věc, kterou jsem ti kdy řekl/a, já na ni už možná zapomněl/a, ale ty ji máš pořád v hlavě?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě vzrušuje představa, že by nás při sexu ''omylem'' přistihl někdo z našich blízkých přátel? (1 = to by byl konec světa, 5 = hrozně mě to láká)'),
  ('tier_2', 'yes_no', 'Byl/a bys pro, abych ti právě teď v posteli zavázal/a oči a přejížděl/a po tobě kostkou ledu?'),
  ('tier_2', 'short_answer', 'Kdybys mohl/a mávnutím kouzelného proutku změnit jednu fyzickou vlastnost mých genitálií, co by to bylo?'),
  ('tier_2', 'yes_no', 'Použil/a jsi někdy k masturbaci běžný předmět z domácnosti (např. něco z kuchyně, rukojeť)?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi pro ''impact play'' (plácání, výprask) až do takové míry, že ti do druhého dne zůstanou viditelné modřiny? (1 = nechci modřiny, 5 = chci se jimi chlubit)'),
  ('tier_2', 'yes_no', 'Vzrušuje tě myšlenka, že bych kompletně ovládal/a tvoje orgasmy – např. ''ruined orgasm'' (zastavení těsně před vrcholem a nedovolení ho dokončit)?'),
  ('tier_2', 'short_answer', 'Co je ta nejvíc ''slutty'' (děvkovská/prasácká) věc, kterou jsi udělal/a ještě předtím, než jsme se poznali, a jsi na ni tajně pyšný/á?'),
  ('tier_2', 'yes_no', 'Chtěl/a bys zkusit vzájemnou masturbaci ve stavu, kdy budeme oba hodně opilí nebo zkouření?'),
  ('tier_2', 'frequency_1_5', 'Jak moc se ti líbí představa, že si tě ''označkuju'' (kousance, cucfleky na krku) tak, aby to v práci všichni viděli? (1 = to je trapas, 5 = obrovské vzrušení)'),
  ('tier_2', 'yes_no', 'Měl/a jsi někdy při sexu se mnou zavřené oči a myslel/a jsi u toho na konkrétního kolegu nebo kolegyni z práce?'),
  ('tier_2', 'short_answer', 'Jaká sexuální praktika je podle tebe naprosto ''vanilla'' (běžná, klasická), ale přesto ji spolu děláme strašně málo?'),
  ('tier_2', 'yes_no', 'Byl/a bys v pohodě s tím, že bychom měli naše domácí porno uložené ve sdílené cloudové složce pod heslem?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě vzrušuje, když agresivně převezmu kontrolu a prostě si tě vezmu, aniž bych se tě ptal/a na svolení (v rámci nastavených hranic)? (1 = nemám to rád/a, 5 = to je to nejlepší)'),
  ('tier_2', 'yes_no', 'Oblékl/a sis někdy tajně moje spodní prádlo nebo oblečení, aby ses vzrušil/a?'),
  ('tier_2', 'short_answer', 'Kdybychom teď vešli do luxusního swingers klubu plného lidí, do jaké místnosti nebo na jakou aktivitu by ses šel/šla podívat jako první?'),
  ('tier_2', 'yes_no', 'Baví tě, když do tebe jedu ''dirty talk'' už během dne v SMSkách a popisuju, co přesně ti večer udělám?'),
  ('tier_2', 'frequency_1_5', 'Jak moc jsi otevřený/á masáži prostaty (pokud jsi muž) nebo hlubokému análnímu zkoumání prsty (pokud jsi žena)? (1 = nesahat, 5 = chci, abys to prozkoumal/a)'),
  ('tier_2', 'yes_no', 'Považuješ ''somnofilii'' (probuzení polibky, orálem nebo vniknutím, když tvrdě spíš) za překročení hranic, nebo tě to naopak láká?'),
  ('tier_2', 'short_answer', 'Kde na tom nejbizarnějším nebo nejnevhodnějším místě jsi kdy ve svém životě dosáhl/a orgasmu?'),
  ('tier_2', 'yes_no', 'Předstíral/a jsi někdy orgasmus prostě proto, že už tě bolela ruka, pusa nebo tělo a chtěl/a jsi, ať už je konec?'),
  ('tier_2', 'frequency_1_5', 'Jak moc toužíš po tom, abych tě při orálním sexu opravdu silně tahal/a za vlasy a držel/a ti hlavu? (1 = ne, bolí to, 5 = bez toho to není ono)'),
  ('tier_2', 'yes_no', 'Kývl/a bys na víkendovou ''propustku'', pokud bychom jeli na dovolenou každý zvlášť (ty s partou, já s partou)?'),
  ('tier_2', 'short_answer', 'Jakou naprosto konkrétní, sprostou větu bys chtěl/a, abych zařval/a těsně v momentě, kdy dělám udělám/kdy vyvrcholíš?'),
  ('tier_2', 'yes_no', 'Ochutnal/a jsi někdy záměrně (např. při líbání po orálu) svoje vlastní tělní tekutiny a líbilo se ti to?'),
  ('tier_2', 'frequency_1_5', 'Jak moc by tě vzrušovalo koukat se na mě, jak uspokojuji někoho jiného? (1 = zlomilo by mi to srdce, 5 = je to obří fetiš)'),
  ('tier_2', 'yes_no', 'Měl/a jsi někdy byť i letmou sexuální myšlenku na někoho z mých sourozenců nebo blízkých příbuzných?'),
  ('tier_2', 'short_answer', 'Kdybys byl/a na 24 hodin mým naprostým Pánem/Paní, jaký by byl první ponižující nebo úchylný úkol, který bys mi zadal/a?'),
  ('tier_2', 'frequency_1_5', 'Jak moc si užíváš tzv. ''aftercare'' (třeba i to, že ti donesu vodu a přikryju tě) po opravdu tvrdém, až zvířecím sexu? (1 = nepotřebuju to, 5 = je to klíčové pro můj pocit bezpečí)'),
  ('tier_2', 'yes_no', 'Byl/a bys otevřený/á tomu, že bych si nasadil/a strap-on dildo a použil/a ho na tobě (bez ohledu na to, jakého jsme pohlaví)?'),
  ('tier_2', 'yes_no', 'Sledoval/a jsi mě někdy tajně klíčovou dírkou nebo pootevřenými dveřmi, když jsem se sprchoval/a nebo převlékal/a?'),
  ('tier_2', 'short_answer', 'Jakou přesnou kategorii na Pornhubu (nebo jinde) si zadáš, když máš na masturbaci přesně 2 minuty a potřebuješ to hned?'),
  ('tier_2', 'frequency_1_5', 'Jak moc se ti líbí extrémní veřejné projevy náklonnosti (tvrdé osahávání, hluboké líbání) v nacpaném baru nebo klubu? (1 = stydím se, 5 = strašně mě to nabíjí)'),
  ('tier_2', 'yes_no', 'Nechal/a bys mě, abych ti celý jeden týden vybíral/a spodní prádlo (nebo jeho absenci) bez možnosti to odmítnout?'),
  ('tier_2', 'yes_no', 'Vzrušuje tě ''breeding fetish'' – tedy fantazie o dělání dětí (creampie, stříkání dovnitř), i když jsme chránění nebo děti nechceme?'),
  ('tier_2', 'short_answer', 'Kdybychom od zítřka směli až do konce života používat jen JEDNU jedinou sexuální polohu, kterou bys vybral/a, aby tě to uspokojilo?'),
  ('tier_2', 'frequency_1_5', 'Jak otevřený/á jsi hrátkám s horkým voskem z BDSM svíček kapaným přímo na kůži? (1 = bojím se popálenin, 5 = kapej to na mě)'),
  ('tier_2', 'yes_no', 'Vyvolal/a jsi někdy záměrně hádku jen proto, že jsi pak měl/a hroznou chuť na ''make-up sex'' (usmiřovací sex)?'),
  ('tier_2', 'yes_no', 'Byl/a bys ochotný/á se mnou zajít na specializovaný BDSM workshop (kurz vázání, bičování), abychom se to naučili profi?'),
  ('tier_2', 'short_answer', 'Dělám při sexu něco, co ti přijde vlastně trochu neohrabané nebo vtipné, ale protože je to roztomilé, tak mi to toleruješ?'),
  ('tier_2', 'frequency_1_5', 'Jak moc se ti líbí senzorická deprivace (např. páska přes oči plus sluchátka s hlukem), abys naprosto ztratil/a orientaci, zatímco si s tebou budu hrát? (1 = děsí mě to, 5 = absolutní fetiš)'),
  ('tier_2', 'yes_no', 'Představoval/a sis někdy detailně, jak by to vypadalo a co bychom dělali, kdyby nás při sexu v autě vyrušila policejní hlídka?'),
  ('tier_2', 'yes_no', 'Zvažoval/a bys, že bychom si nechali udělat tajné, párové tetování se sexuálním podtextem na skrytém místě?'),
  ('tier_2', 'short_answer', 'Jaký je nejlepší způsob, jak se tě na veřejnosti dotknout, abys okamžitě věděl/a, že tě chci ojet, ale nikdo jiný v místnosti si toho nevšiml?'),
  ('tier_2', 'frequency_1_5', 'Jak moc tě láká mít v sobě vibrační vajíčko/kolík ovládaný mnou přes aplikaci během toho, co budeme na formální večeři u mých rodičů? (1 = to je úchylné, 5 = hned to kup)'),
  ('tier_2', 'yes_no', 'Žárlil/a jsi někdy na moji sexuální hračku, protože jsi měl/a pocit, že mi dělá lépe než ty?'),
  ('tier_2', 'yes_no', 'Nechal/a bys mě, abych ti kompletně oholil/a nebo upravil/a ohanbí břitvou přesně podle svých představ?'),
  ('tier_2', 'short_answer', 'Jaká je absolutně nejvíc prasácká myšlenka, kterou jsi o mně měl/a v průběhu dnešního dne?'),
  ('tier_2', 'frequency_1_5', 'Jak moc souhlasíš s tvrzením: ''Sex bez hlubokého citového propojení je vlastně jen taková gymnastika.''? (1 = absolutně nesouhlasím, sex je sex, 5 = naprosto souhlasím)'),
  ('tier_2', 'yes_no', 'Máš občas chuť, abych byl/a v posteli vyloženě sobecký/á a prostě si vzal/a to, co chci já, bez ohledu na tebe?'),
  ('tier_2', 'yes_no', 'Kdyby se ukázalo, že se v této aplikaci shodneme v našich nejdivočejších fantaziích, měl/a bys reálnou odvahu to se mnou zkusit hned dnes večer?')
on conflict do nothing;
